### ISSUE TITLE
return value of "ca.noxid.lab.rsrc.ResourceManager.getImg(java.io.File)" is null

### ISSUE THREAD

**Issue by NancokPS2** [taedixon/boosters-lab#35]
So apparently the thing is having issues loading some png files, i tried with different MODE and BITMAPMODE configurations but they just cause the program to crash    
  
Sample of file causing issues  
![ItemImage](https://user-images.githubusercontent.com/55665720/210470675-4dec75b8-69d1-4c2a-b6bc-881facdb503b.png)  
  
Using doukutsu-rs which is apparently an improved version of the freeware version, altho the files are the same as the original game
    
This only happens on some maps, like Mimi.pxm. But Start.pxm, Shelt.pxm and Cemet.pxm do not have any issues outside of missing tile textures in the editor  

Log:
F:\Downloads\CS Repainted\MouskaTools\Text and Tiles\BoostLab0512C>java -jar BoostLab.jar "MODE=0" "BITMAPMODE=1"
Key not found for getImgGraphics
F:\Downloads\CS Repainted\doukutsu-rs_0.99.0_beta4_win64\data\ItemImage.png
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getSubimage(int, int, int, int)" because the return value of "ca.noxid.lab.rsrc.ResourceManager.getImg(java.io.File)" is null
        at ca.noxid.lab.script.TscPane.addCommandExtra(TscPane.java:451)
        at ca.noxid.lab.script.TscPane.setCommandExtras(TscPane.java:328)
        at ca.noxid.lab.script.TscPane$4.caretUpdate(TscPane.java:296)
        at java.desktop/javax.swing.text.JTextComponent.fireCaretUpdate(JTextComponent.java:412)
        at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4491)
        at java.desktop/javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4513)
        at java.desktop/javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:842)
        at java.desktop/javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1313)
        at java.desktop/javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1212)
        at java.desktop/javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1193)
        at java.desktop/javax.swing.text.DefaultCaret$Handler.insertUpdate(DefaultCaret.java:1789)
        at java.desktop/javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:226)
        at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:780)
        at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:739)
        at java.desktop/javax.swing.text.DefaultEditorKit.read(DefaultEditorKit.java:239)
        at java.desktop/javax.swing.JEditorPane.setText(JEditorPane.java:1484)
        at ca.noxid.lab.script.TscPane.loadFile(TscPane.java:171)
        at ca.noxid.lab.script.TscPane.<init>(TscPane.java:117)
        at ca.noxid.lab.EditorApp.addMapTab(EditorApp.java:2028)
        at ca.noxid.lab.EditorApp.actionPerformed(EditorApp.java:2147)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
        at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)

        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by NancokPS2** [comment]
Turns out, you should not load individual levels, and instead load mrmap.bin  
I totally knew that, i was testing if the issue forms worked, yeah
